<h1>本章目录<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#数据挖掘常用模块" data-toc-modified-id="数据挖掘常用模块-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>数据挖掘常用模块</a></span><ul class="toc-item"><li><span><a href="#数组与向量化计算：numpy" data-toc-modified-id="数组与向量化计算：numpy-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>数组与向量化计算：numpy</a></span><ul class="toc-item"><li><span><a href="#NumPy的ndarray：一种多维数组对象" data-toc-modified-id="NumPy的ndarray：一种多维数组对象-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>NumPy的ndarray：一种多维数组对象</a></span><ul class="toc-item"><li><span><a href="#创建ndarray" data-toc-modified-id="创建ndarray-3.1.1.1"><span class="toc-item-num">3.1.1.1&nbsp;&nbsp;</span>创建ndarray</a></span></li><li><span><a href="#ndarray的数据类型" data-toc-modified-id="ndarray的数据类型-3.1.1.2"><span class="toc-item-num">3.1.1.2&nbsp;&nbsp;</span>ndarray的数据类型</a></span></li><li><span><a href="#NumPy数组的运算" data-toc-modified-id="NumPy数组的运算-3.1.1.3"><span class="toc-item-num">3.1.1.3&nbsp;&nbsp;</span>NumPy数组的运算</a></span></li><li><span><a href="#基本的索引和切片" data-toc-modified-id="基本的索引和切片-3.1.1.4"><span class="toc-item-num">3.1.1.4&nbsp;&nbsp;</span>基本的索引和切片</a></span></li><li><span><a href="#切片索引" data-toc-modified-id="切片索引-3.1.1.5"><span class="toc-item-num">3.1.1.5&nbsp;&nbsp;</span>切片索引</a></span></li><li><span><a href="#布尔型索引" data-toc-modified-id="布尔型索引-3.1.1.6"><span class="toc-item-num">3.1.1.6&nbsp;&nbsp;</span>布尔型索引</a></span></li><li><span><a href="#花式索引" data-toc-modified-id="花式索引-3.1.1.7"><span class="toc-item-num">3.1.1.7&nbsp;&nbsp;</span>花式索引</a></span></li><li><span><a href="#数组转置和轴对换" data-toc-modified-id="数组转置和轴对换-3.1.1.8"><span class="toc-item-num">3.1.1.8&nbsp;&nbsp;</span>数组转置和轴对换</a></span></li></ul></li><li><span><a href="#通用函数：快速的元素级数组函数" data-toc-modified-id="通用函数：快速的元素级数组函数-3.1.2"><span class="toc-item-num">3.1.2&nbsp;&nbsp;</span>通用函数：快速的元素级数组函数</a></span></li><li><span><a href="#利用数组进行数据处理" data-toc-modified-id="利用数组进行数据处理-3.1.3"><span class="toc-item-num">3.1.3&nbsp;&nbsp;</span>利用数组进行数据处理</a></span><ul class="toc-item"><li><span><a href="#将条件逻辑表述为数组运算" data-toc-modified-id="将条件逻辑表述为数组运算-3.1.3.1"><span class="toc-item-num">3.1.3.1&nbsp;&nbsp;</span>将条件逻辑表述为数组运算</a></span></li><li><span><a href="#数学和统计方法" data-toc-modified-id="数学和统计方法-3.1.3.2"><span class="toc-item-num">3.1.3.2&nbsp;&nbsp;</span>数学和统计方法</a></span></li><li><span><a href="#用于布尔型数组的方法" data-toc-modified-id="用于布尔型数组的方法-3.1.3.3"><span class="toc-item-num">3.1.3.3&nbsp;&nbsp;</span>用于布尔型数组的方法</a></span></li><li><span><a href="#排序" data-toc-modified-id="排序-3.1.3.4"><span class="toc-item-num">3.1.3.4&nbsp;&nbsp;</span>排序</a></span></li><li><span><a href="#唯一化以及其它的集合逻辑" data-toc-modified-id="唯一化以及其它的集合逻辑-3.1.3.5"><span class="toc-item-num">3.1.3.5&nbsp;&nbsp;</span>唯一化以及其它的集合逻辑</a></span></li></ul></li><li><span><a href="#线性代数" data-toc-modified-id="线性代数-3.1.4"><span class="toc-item-num">3.1.4&nbsp;&nbsp;</span>线性代数</a></span></li><li><span><a href="#伪随机数生成" data-toc-modified-id="伪随机数生成-3.1.5"><span class="toc-item-num">3.1.5&nbsp;&nbsp;</span>伪随机数生成</a></span></li></ul></li></ul></li></ul></div>

# 数据挖掘常用模块

在本实验课程中，将主要用到以下模块:

* **numpy**: 数值计算.
* **pandas**: 数据分析常用包，尤其是前期数据预处理
* **scikit-learn**: 经典的机器学习库
* **matplotlib**: 基础绘图库，为其他众多绘图包提供了基础
* **seaborn**: 高级统计图形包  

人们应对复杂性的最有效办法，便是分层切块。Python对于代码的组织管理，采用的是模块module的方式；也通常会将功能相近的模块打成包package进行分发，尤其是对于熟悉R语言的同学来讲，包package的概念可能更加亲切，不过python的包其实还是模块module，还是在分层切块，便于代码管理和复用。当然，除了模块和包之外，另一个概念是库library。代码库、或者说程序库对于任何语言来讲，都是通用的说法。在后续的表述中，可能模块module、包package、库library可能会交叉使用。

## 数组与向量化计算：numpy

numpy = **Num**erical **Py**thon

NumPy是 Python 提供进行科学计算的基础模块，提供了快速高效的向量化计算，以及线性代数等高级矩阵运算功能。可以毫不夸张的说，NumPy是Python数值计算最重要的基础包。大多数提供科学计算的包都是用NumPy的数组作为构建基础。Python之所以能在科学计算上独领风骚很大程度上就是因为这个库。  

NumPy的部分功能如下：
* 一个具有矢量算术运算和复杂广播能力的快速且节省空间的多维数组ndarray（N-dimensional array object）。
* 用于对整组数据进行快速运算的数学运算。向量化运算，无需编写循环。提供了大量的标准数学函数ufunc(universal function object)。
* 用于读写磁盘数据的工具以及用于操作内存映射文件的工具。
* 实用的线性代数、傅里叶变换和随机数生成函数。numpy和稀疏矩阵运算包scipy配合使用更加方便。
* 用于整合C/C++和Fortran代码的工具包。

NumPy本身并没有提供多么高级的数据分析功能，理解NumPy数组以及面向数组的计算将有助于你更加高效地使用诸如pandas之类的工具。很多机器学习库都是基于numpy。

NumPy之于数值计算特别重要的原因之一，是因为它可以高效处理大数组的数据。这是因为：
* NumPy是在一个连续的内存块中存储数据，独立于其他Python内置对象。
* NumPy的C语言编写的算法库可以操作内存，而不必进行类型检查或其它前期工作。比起Python的内置序列，NumPy数组使用的内存更少。
* NumPy可以在整个数组上执行复杂的计算，而不需要Python的for循环。

In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

各个序列分别乘以2：

In [2]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 46 ms


In [3]:
 %time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 2.01 s


基于NumPy的算法要比纯Python快10到100倍（甚至更快），并且使用的内存更少。除了内存使用和时间效率外，对于大部分R的用户而言，numpy所体现出来的面向数组的编程和思维方式，将会赶到特别亲切。

### NumPy的ndarray：一种多维数组对象

NumPy最重要的一个特点就是其N维数组对象（即ndarray），该对象是一个快速而灵活的大数据集容器。你可以利用这种数组对整块数据执行一些数学运算，其语法跟标量元素之间的运算一样。

In [4]:
import numpy as np

In [5]:
data = np.random.randn(2, 3)
data

array([[-1.27536455,  0.70541497,  0.73617122],
       [ 0.91847409,  1.36676879,  1.21007426]])

In [6]:
data * 10

array([[-12.75364555,   7.05414969,   7.36171217],
       [  9.18474091,  13.66768785,  12.10074264]])

In [7]:
data + data

array([[-2.55072911,  1.41082994,  1.47234243],
       [ 1.83694818,  2.73353757,  2.42014853]])

第一个例子中，所有的元素都乘以10。第二个例子中，每个元素都与自身相加

ndarray是一个通用的同构数据多维容器，也就是说，其中的所有元素必须是相同类型的。每个数组都有一个shape（一个表示各维度大小的元组）和一个dtype（一个用于说明数组数据类型的对象）：

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

#### 创建ndarray

创建数组最简单的办法就是使用array函数。它接受一切序列型的对象（包括其他数组），然后产生一个新的含有传入数据的NumPy数组。以一个列表的转换为例：

In [10]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

嵌套序列（比如由一组等长列表组成的列表）将会被转换为一个多维数组：

In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

因为data2是列表的列表，NumPy数组arr2的两个维度的shape是从data2引入的。可以用属性ndim和shape验证：

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

ndarray一些基本属性：  
* ndim 维度数量
* shape是一个表示各维度大小的元组，即数组的形状
* dtype，一个用于说明数组元素数据类型的对象
* size，元素总个数，即shape中各数组相乘

除非特别说明（稍后将会详细介绍），np.array会尝试为新建的这个数组推断出一个较为合适的数据类型。数据类型保存在一个特殊的dtype对象中。比如说，在上面的两个例子中，我们有：

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int32')

除np.array之外，还有一些函数也可以新建数组。比如，zeros和ones分别可以创建指定长度或形状的全0或全1数组。empty可以创建一个没有任何具体值的数组。要用这些方法创建多维数组，只需传入一个表示形状的元组即可：

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.empty((2, 3, 2))

array([[[8.79312534e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.97916441e+179]],

       [[4.79582619e-037, 6.74929599e-067],
        [2.69644148e+184, 3.40791889e+175],
        [1.20962924e+161, 2.73898529e-057]]])

简单归纳一下：  
* array函数：接收一个普通的Python序列，转成ndarray
* zeros函数：创建指定长度或形状的全零数组
* ones函数：创建指定长度或形状的全1数组
* empty函数：创建一个没有任何具体值的数组（准确地说是一些未初始化的垃圾值）

arange是Python内置函数range的数组版：

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

简单归纳一下数组的其他一些创建方式：  
* **arrange**：类似于python的range函数，通过指定开始值、终值和步长来创建一维数组，注意数组不包括终值
* **linspace**：通过指定开始值、终值和元素个数来创建一维数组（等差数列），可以通过endpoint关键字指定是否包括终值，缺省设置是包括终值
* **logspace**：和linspace类似，不过它创建等比数列
* 使用随机数填充数组，即使用numpy.random模块的random()函数，数组所包含的的元素数量由参数决定

下表是《Python基础教程》列举的创建数组常用方法：
![img](figtabs/ch3/python_for_data_analysis_table4.1.png)

#### ndarray的数据类型

dtype（数据类型）是一个特殊的对象，它含有ndarray将一块内存解释为特定数据类型所需的信息：

In [20]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [21]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int32')

数值型dtype的命名方式相同：一个类型名（如float或int），后面跟一个用于表示各元素位长的数字。标准的双精度浮点值（即Python中的float对象）需要占用8字节（即64位）。因此，该类型在NumPy中就记作float64。
![img](figtabs/ch3/python_for_data_analysis_table4.2.png)

可以通过ndarray的astype方法明确地将一个数组从一个dtype转换成另一个dtype。有需要的时候，我们可以进行下述转换以节省空间： 
* int64-->int32
* float64-->float32

这里的8/16/32/64表示占用字节数，比如，对于整型而言：  
* int8，字节（-128 ~ 127），1个字节
* int16，整型（-32768 ~ 32767），2个字节
* int32，整型（-2147483648 ~ 2147483647），4个字节
* int64，整型（- 9223372036854775808~9223372036854775807），8字节

再比如，对于浮点数而言：  
* float16：符号位，5位指数，10位小数部分
* float32：符号位，8位指数，23位小数部分
* float64：符号位，11位指数，52位小数部分

又比如，对于复数而言：  
* complex64：由两个32位的浮点数来表示（实数部分和虚数部分）
* complex128：由两个64位的浮点数来表示（实数部分和虚数部分）

也有一些简写的方式：  
* int_：默认整型（与C中的long相同，通常为int64或者int32）
* float_：float64的简写形式
* comlex_：complex128的简写形式

其实，大部分时候，我们都无需关注这些细节。

In [24]:
arr = np.array([1, 2, 3, 4, 5])

In [25]:
arr.dtype

dtype('int32')

In [26]:
float_arr = arr.astype(np.float64)

In [27]:
float_arr.dtype

dtype('float64')

如果将浮点数转换成整数，则小数部分将会被截取删除：

In [28]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

如果某字符串数组表示的全是数字，也可以用astype将其转换为数值形式：

In [29]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [30]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

#### NumPy数组的运算

数组很重要，因为它使你不用编写循环即可对数据执行批量运算。NumPy用户称其为向量化（vectorization）。大小相等的数组之间的任何算术运算都会将运算应用到元素级：

In [31]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [33]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

数组与标量的算术运算会将标量值传播到各个元素：

In [34]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [35]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

大小相同的数组之间的比较会生成布尔值数组：

In [36]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [37]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

#### 基本的索引和切片

NumPy数组的索引是一个内容丰富的主题，因为选取数据子集或单个元素的方式有很多。一维数组很简单。从表面上看，它们跟Python列表的功能差不多：

In [38]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[5:8]

array([5, 6, 7])

In [40]:
arr[5:8] = 12

如上所示，当你将一个标量值赋值给一个切片时（如arr[5:8]=12），该值会自动传播到整个选区。跟列表最重要的区别在于，数组切片是原始数组的视图。这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上。

In [41]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

当我修稿arr_slice中的值，变动也会体现在原始数组arr中：

In [42]:
arr_slice[1] = 12345

In [43]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

切片[ : ]会给数组中的所有值赋值：

In [44]:
arr_slice[:] = 64

In [45]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

如果你刚开始接触NumPy，可能会对此感到惊讶（比如和R语言相比）。由于NumPy的设计目的是处理大数据，所以你可以想象一下，假如NumPy坚持要将数据复制来复制去的话会产生何等的性能和内存问题。

对于高维度数组，能做的事情更多。在一个二维数组中，各索引位置上的元素不再是标量而是一维数组：

In [46]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [47]:
arr2d[2]

array([7, 8, 9])

因此，可以对各个元素进行递归访问，但这样需要做的事情有点多。你可以传入一个以逗号隔开的索引列表来选取单个元素。也就是说，下面两种方式是等价的：

In [48]:
arr2d[0][2]

3

In [49]:
arr2d[0, 2]

3

下图说明了说明了二维数组的索引方式。轴0作为行，轴1作为列。
![img](figtabs/ch3/python_for_data_analysis_figure4.1.png)

在多维数组中，如果省略了后面的索引，则返回对象会是一个维度低一点的
ndarray（它含有高一级维度上的所有数据）。因此，在2×2×3数组arr3d中：

In [50]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                  [[7, 8, 9], [10, 11, 12]]])

arr3d[0]是一个2×3数组：

In [51]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

标量值和数组都可以被赋值给arr3d[0]：

In [52]:
old_values = arr3d[0].copy()

In [53]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
arr3d[1] = 24
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[24, 24, 24],
        [24, 24, 24]]])

相似的，arr3d[1,0]可以访问索引以(1,0)开头的那些值（以一维数组的形式返回）：

In [55]:
arr3d[1, 0]

array([24, 24, 24])

虽然是用两步进行索引的，表达式是相同的：

In [56]:
x = arr3d[1]
x

array([[24, 24, 24],
       [24, 24, 24]])

In [57]:
x[0]

array([24, 24, 24])

#### 切片索引

ndarray的切片语法跟Python列表这样的一维对象差不多：

In [58]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [59]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

对于之前的二维数组arr2d，其切片方式稍显不同：

In [60]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

可以看出，它是沿着第0轴（即第一个轴）切片的。也就是说，切片是沿着一个轴向选取元素的。表达式arr2d[:2]可以被认为是“选取arr2d的前两行”。  
你可以一次传入多个切片，就像传入多个索引那样：

In [62]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

像这样进行切片时，只能得到相同维数的数组视图。通过将整数索引和切片混合，可以得到低维度的切片。  
例如，我可以选取第二行的前两列：

In [63]:
arr2d[1, :2]

array([4, 5])

“只有冒号”表示选取整个轴，因此你可以像下面这样只对高维轴进行切片：

In [64]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

![img](figtabs/ch3/python_for_data_analysis_figure4.2.png)

#### 布尔型索引

来看这样一个例子，假设我们有一个用于存储数据的数组以及一个存储姓名的数组（含有重复项）。在这里，我将使用numpy.random中的randn函数生成一些正态分布的随机数据：

In [65]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob',
                  'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [66]:
data = np.random.randn(7, 4)
data

array([[-1.13734345,  0.36464719,  0.67967956, -0.56945424],
       [ 1.66751654, -0.69073255, -0.68408038,  2.08589929],
       [-1.00910501,  0.84785144,  0.16527574, -1.12520915],
       [-0.06867292, -0.61328777,  0.34281526,  0.30916645],
       [-0.69266271,  0.37666151, -0.02298039, -1.7696272 ],
       [ 0.30776315,  1.24724794, -0.30142079,  2.25861625],
       [ 1.31573983, -0.35941603, -0.55898174, -0.18261664]])

假设每个名字都对应data数组中的一行，而我们想要选出对应于名字"Bob"的所有行。跟算术运算一样，数组的比较运算（如==）也是矢量化的。因此，对names和字符串"Bob"的比较运算将会产生一个布尔型数组：

In [67]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

这个布尔型数组可用于数组索引：

In [68]:
data[names == 'Bob']

array([[-1.13734345,  0.36464719,  0.67967956, -0.56945424],
       [-0.06867292, -0.61328777,  0.34281526,  0.30916645]])

布尔型数组的长度必须跟被索引的轴长度一致。此外，还可以将布尔型数组跟切片、整数混合使用：

In [69]:
data[names == 'Bob']

array([[-1.13734345,  0.36464719,  0.67967956, -0.56945424],
       [-0.06867292, -0.61328777,  0.34281526,  0.30916645]])

In [70]:
data[names == 'Bob', 2:]

array([[ 0.67967956, -0.56945424],
       [ 0.34281526,  0.30916645]])

要选择除"Bob"以外的其他值，既可以使用不等于符号（!=），也可以通过~对条件进行否定：

In [71]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [72]:
data[~(names == 'Bob')]

array([[ 1.66751654, -0.69073255, -0.68408038,  2.08589929],
       [-1.00910501,  0.84785144,  0.16527574, -1.12520915],
       [-0.69266271,  0.37666151, -0.02298039, -1.7696272 ],
       [ 0.30776315,  1.24724794, -0.30142079,  2.25861625],
       [ 1.31573983, -0.35941603, -0.55898174, -0.18261664]])

~操作符用来反转条件很好用：

In [73]:
cond = names == 'Bob'

In [74]:
data[~cond]

array([[ 1.66751654, -0.69073255, -0.68408038,  2.08589929],
       [-1.00910501,  0.84785144,  0.16527574, -1.12520915],
       [-0.69266271,  0.37666151, -0.02298039, -1.7696272 ],
       [ 0.30776315,  1.24724794, -0.30142079,  2.25861625],
       [ 1.31573983, -0.35941603, -0.55898174, -0.18261664]])

选取这三个名字中的两个需要组合应用多个布尔条件，使用&（和）、|（或）之类的布尔算术运算符即可（Python关键字and和or在布尔型数组中无效。要使用&与|）：

In [75]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [76]:
data[mask]

array([[-1.13734345,  0.36464719,  0.67967956, -0.56945424],
       [-1.00910501,  0.84785144,  0.16527574, -1.12520915],
       [-0.06867292, -0.61328777,  0.34281526,  0.30916645],
       [-0.69266271,  0.37666151, -0.02298039, -1.7696272 ]])

通过布尔型数组设置值是一种经常用到的手段。为了将data中的所有负值都设置为0，我们只需：

In [77]:
data[data < 0] = 0
data

array([[0.        , 0.36464719, 0.67967956, 0.        ],
       [1.66751654, 0.        , 0.        , 2.08589929],
       [0.        , 0.84785144, 0.16527574, 0.        ],
       [0.        , 0.        , 0.34281526, 0.30916645],
       [0.        , 0.37666151, 0.        , 0.        ],
       [0.30776315, 1.24724794, 0.        , 2.25861625],
       [1.31573983, 0.        , 0.        , 0.        ]])

通过一维布尔数组设置整行或列的值也很简单：

In [78]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.66751654, 0.        , 0.        , 2.08589929],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.30776315, 1.24724794, 0.        , 2.25861625],
       [1.31573983, 0.        , 0.        , 0.        ]])

#### 花式索引

花式索引（Fancy indexing）是一个NumPy术语，它指的是利用整数数组进行索引。假设我们有一个8×4数组：

In [79]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

为了以特定顺序选取行子集，只需传入一个用于指定顺序的整数列表或ndarray即可：

In [80]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

使用负数索引将会从末尾开始选取行：

In [81]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

一次传入多个索引数组会有一点特别。它返回的是一个一维数组，其中的元素对应各个索引元组：

In [82]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [83]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

最终选出的是元素(1,0)、(5,3)、(7,1)和(2,2)。无论数组是多少维的，花式索引总是一维的。  
这个花式索引的行为可能会跟我们的预期不一样，选取矩阵的行列子集应该是矩形区域的形式才对。下面是得到该结果的一个办法：

In [84]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

花式索引跟切片不一样，它总是将数据复制到新数组中。

#### 数组转置和轴对换

转置是重塑的一种特殊形式，它返回的是源数据的视图（不会进行任何复制操作）。数组不仅有transpose方法，还有一个特殊的T属性：

In [85]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

在进行矩阵计算时，经常需要用到该操作，比如利用np.dot计算矩阵内积：

In [87]:
arr = np.random.randn(6, 3)
arr

array([[-0.55949669, -1.7107798 , -0.69875997],
       [ 0.54025393, -2.300683  , -1.16340795],
       [-0.55693949, -0.62912571,  1.27629269],
       [ 0.88029659,  0.88109633,  0.98700963],
       [ 0.25422631, -1.77940518,  0.94244276],
       [-1.24046306,  0.20727383,  0.05107631]])

In [88]:
np.dot(arr.T, arr)

array([[ 3.29339415,  0.13074649,  0.09669704],
       [ 0.13074649, 12.60128493,  2.27235859],
       [ 0.09669704,  2.27235859,  5.33570176]])

### 通用函数：快速的元素级数组函数

通用函数（即ufunc）是一种对ndarray中的数据执行元素级运算的函数。你可以将其看做简单函数（接受一个或多个标量值，并产生一个或多个标量值）的矢量化包装器。  
许多ufunc都是简单的元素级变体，如sqrt和exp：

In [89]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [91]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

这些都是一元（unary）ufunc。另外一些（如add或maximum）接受2个数组（因此也叫二元（binary）ufunc），并返回一个结果数组：

In [92]:
x = np.random.randn(8)
x

array([-0.93739766, -0.05814833, -1.25610443, -0.66881934, -0.32009404,
       -0.37354266, -0.57058439, -0.49174097])

In [93]:
y = np.random.randn(8)
y

array([ 0.58537307,  0.32908052,  0.83023402, -1.73554966, -1.51142128,
       -0.99202578, -1.14252086, -1.02285894])

In [94]:
np.maximum(x, y)

array([ 0.58537307,  0.32908052,  0.83023402, -0.66881934, -0.32009404,
       -0.37354266, -0.57058439, -0.49174097])

以下分别是一元和二元ufunc：
![img](figtabs/ch3/python_for_data_analysis_table4.3.png)
![img](figtabs/ch3/python_for_data_analysis_table4.4.png)

### 利用数组进行数据处理

NumPy数组使你可以将许多种数据处理任务表述为简洁的数组表达式（否则需要编写循环）。用数组表达式代替循环的做法，通常被称为向量化。一般来说，向量化数组运算要比等价的纯Python方式快上一两个数量级（甚至更多），尤其是各种数值计算。

In [95]:
points1 = np.arange(1, 4)
points2 = np.arange(5, 7)

In [96]:
xs, ys = np.meshgrid(points1, points2)
xs

array([[1, 2, 3],
       [1, 2, 3]])

In [97]:
ys

array([[5, 5, 5],
       [6, 6, 6]])

np.meshgrid函数接受两个一维数组，并产生两个二维矩阵，对应于两个数组中所有的(x,y)对）：  
(1, 5) (2, 5) (3, 5)  
(1, 6) (2, 6) (3, 6)

In [98]:
import numpy as np
points = np.arange(-5, 5, 0.01)
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [99]:
xs, ys = np.meshgrid(points, points)
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [100]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

现在，对该函数的求值运算就好办了，把这两个数组当做两个浮点数那样编写表达式即可：

In [101]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

用matplotlib创建了这个二维数组的可视化：

In [102]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray)
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")
plt.show()

<Figure size 640x480 with 2 Axes>

np.meshgrid函数接受两个一维数组，并产生两个二维矩阵（对应于两个数组中所有的(x,y)对）：

#### 将条件逻辑表述为数组运算

numpy.where函数是三元表达式x if condition else y的矢量化版本。假设我们有一个布尔数组和两个值数组：

In [103]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

假设我们想要根据cond中的值选取xarr和yarr的值：当cond中的值为True时，选取xarr的值，否则从yarr中选取。

In [104]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

np.where函数是三元表达式 x if condition else y的矢量化版本（或者说向量化版本，矢量化、向量化将在课程中交替使用）。

np.where的第二个和第三个参数不必是数组，它们都可以是标量值。在数据分析工作中，where通常用于根据另一个数组而产生一个新的数组。假设有一个由随机数据组成的矩阵，你希望将所有正值替换为2，将所有负值替换为－2。若利用np.where，则会非常简单：

In [105]:
arr = np.random.randn(4, 4)
arr

array([[ 1.91511485,  2.20748072, -0.69815896,  0.30437388],
       [ 1.52711912, -0.50384253,  0.5602784 , -0.482814  ],
       [-0.11439234, -2.39051083, -1.91341936, -0.40320156],
       [-0.53248739, -0.63513157, -1.49687452, -0.10980343]])

In [106]:
arr > 0

array([[ True,  True, False,  True],
       [ True, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [107]:
np.where(arr > 0, 2, -2)

array([[ 2,  2, -2,  2],
       [ 2, -2,  2, -2],
       [-2, -2, -2, -2],
       [-2, -2, -2, -2]])

使用np.where，可以将标量和数组结合起来。例如，我可用常数2替换arr中所有正的值：

In [108]:
np.where(arr > 0, 2, arr) 

array([[ 2.        ,  2.        , -0.69815896,  2.        ],
       [ 2.        , -0.50384253,  2.        , -0.482814  ],
       [-0.11439234, -2.39051083, -1.91341936, -0.40320156],
       [-0.53248739, -0.63513157, -1.49687452, -0.10980343]])

#### 数学和统计方法

可以通过数组上的一组数学函数对整个数组或某个轴向的数据进行统计计算。sum、mean以及标准差std等聚合计算（aggregation，通常叫做约简
（reduction））既可以当做数组的实例方法调用，也可以当做顶级NumPy函数使用。  
这里，我生成了一些正态分布随机数据，然后进行统计：

In [109]:
arr = np.random.randn(5, 4)
arr

array([[-0.23151381,  0.52838089,  1.33011748, -1.71601815],
       [-0.54986563, -2.28299123,  1.35258587,  0.35065875],
       [-1.13476101, -0.0396544 ,  0.49915669,  0.83662105],
       [ 1.02881025, -1.169263  ,  0.98451874, -0.13375299],
       [-0.62677587,  1.70602959,  1.03669715, -0.43827223]])

In [110]:
arr.mean()

0.0665354072944612

In [111]:
np.mean(arr)

0.0665354072944612

In [112]:
arr.sum()

1.330708145889224

mean和sum这类的函数可以接受一个axis选项参数，用于计算该轴向上的统计值，最终结果是一个少一维的数组：

In [113]:
arr.mean(axis=1)

array([-0.0222584 , -0.28240306,  0.04034059,  0.17757825,  0.41941966])

In [114]:
arr.sum(axis=0)

array([-1.51410606, -1.25749816,  5.20307593, -1.10076357])

这里，arr.mean(1)是“计算行的平均值”，arr.sum(0)是“计算每列的和”

In [115]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [116]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [117]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

一些常用的统计方法：
![img](figtabs/ch3/python_for_data_analysis_table4.5.png)

#### 用于布尔型数组的方法

在上面这些方法中，布尔值会被强制转换为1（True）和0（False）。因此，sum经常被用来对布尔型数组中的True值计数：

In [118]:
arr = np.random.randn(100)
(arr > 0).sum()

51

另外还有两个方法any和all，它们对布尔型数组非常有用。any用于测试数组中是否存在一个或多个True，而all则检查数组中所有值是否都是True：

In [119]:
bools = np.array([False, False, True, False])

In [120]:
bools.any()

True

In [121]:
bools.all()

False

#### 排序

跟Python内置的列表类型一样，NumPy数组也可以通过sort方法就地排序：

In [122]:
arr = np.random.randn(6)
arr

array([ 0.16699461, -1.27714255,  0.38961932, -0.46633796,  0.29193284,
        0.51915143])

In [123]:
arr.sort()
arr

array([-1.27714255, -0.46633796,  0.16699461,  0.29193284,  0.38961932,
        0.51915143])

多维数组可以在任何一个轴向上进行排序，只需将轴编号传给sort即可：

In [124]:
arr = np.array([[2, 3, 1],
                [4, 19, 0],
                [15, 3, 17]])
arr

array([[ 2,  3,  1],
       [ 4, 19,  0],
       [15,  3, 17]])

In [125]:
arr.sort(1)
arr

array([[ 1,  2,  3],
       [ 0,  4, 19],
       [ 3, 15, 17]])

In [126]:
arr.sort(0)
arr

array([[ 0,  2,  3],
       [ 1,  4, 17],
       [ 3, 15, 19]])

#### 唯一化以及其它的集合逻辑

NumPy提供了一些针对一维ndarray的基本集合运算。最常用的可能要数np.unique了，它用于找出数组中的唯一值并返回已排序的结果：

In [127]:
names = np.array(['Bob', 'Joe', 'Will',
                  'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [128]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

数组的一些集合运算
![img](figtabs/ch3/python_for_data_analysis_table4.5.png)

### 线性代数
线性代数（如矩阵乘法、矩阵分解、行列式以及其他方阵数学等）是任何数组库的重要组成部分。

In [129]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

x.dot(y)等价于np.dot(x, y)：

In [130]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

numpy.linalg中有一组标准的矩阵分解运算以及诸如求逆和行列式之类的东西。它们跟MATLAB和R等语言所使用的是相同的行业标准线性代数库，如BLAS、LAPACK、Intel MKL等：

In [131]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[ 0.43279706, -0.07684754, -0.04578289,  0.10493195, -0.17811044],
       [-0.07684754,  0.43136187,  0.09752765,  0.10886781,  0.17561607],
       [-0.04578289,  0.09752765,  1.25986985,  0.18752606, -0.2631729 ],
       [ 0.10493195,  0.10886781,  0.18752606,  0.26219255, -0.09358285],
       [-0.17811044,  0.17561607, -0.2631729 , -0.09358285,  0.50764535]])

In [132]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  1.28370698e-17, -5.83269160e-17,
         2.64442461e-18,  8.00947581e-17],
       [-6.65660193e-19,  1.00000000e+00,  1.57437063e-17,
        -1.32134505e-17, -4.25728343e-18],
       [ 3.00568475e-17, -1.17078430e-17,  1.00000000e+00,
        -2.84071012e-17,  3.34383489e-17],
       [ 8.77468612e-18,  3.68214032e-17,  5.15614734e-17,
         1.00000000e+00, -9.47340607e-17],
       [ 2.27557468e-16, -6.56021197e-17, -1.39539344e-16,
        -3.94791909e-17,  1.00000000e+00]])

In [133]:
q, r = qr(mat)
q

array([[-0.86147161,  0.12922981,  0.36790873, -0.16174002, -0.28222269],
       [-0.11848707, -0.80132168, -0.00938442, -0.51606392,  0.27827027],
       [-0.13535994,  0.10531801, -0.82432161, -0.34232228, -0.41700736],
       [ 0.39871717,  0.36426265,  0.36494435, -0.7437502 , -0.14828555],
       [-0.25793367,  0.44430177, -0.227738  , -0.19279341,  0.80438316]])

In [134]:
r

array([[-3.70698617, -1.16885249, -0.96247179,  3.74506304, -1.21293364],
       [ 0.        , -4.3929748 ,  0.53486305,  4.05113915,  3.41903526],
       [ 0.        ,  0.        , -1.07767207,  1.93013858, -0.65148675],
       [ 0.        ,  0.        ,  0.        , -3.18154811, -0.96628827],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.58453761]])

常用的一些矩阵操作
![img](figtabs/ch3/python_for_data_analysis_table4.7.png)

### 伪随机数生成

numpy.random模块对Python内置的random进行了补充，增加了一些用于高效生成多种概率分布的样本值的函数。例如，你可以用normal来得到一个标准正态分布的4×4样本数组：

In [135]:
samples = np.random.normal(size=(4, 4))
samples

array([[-0.24383965,  0.65812599, -0.48866946,  0.8368134 ],
       [ 0.40641676, -0.7164852 ,  0.68385968, -0.22356538],
       [ 0.14192255, -0.36788136, -0.43720508,  0.61837317],
       [-1.35247198, -2.3968373 ,  0.05246868,  0.61529929]])

我们说这些都是伪随机数，是因为它们都是通过算法基于随机数生成器种子，在确定性的条件下生成的。你可以用NumPy的np.random.seed更改随机数生成种子：

In [136]:
np.random.seed(2012)

一些常用的与随机数相关的函数：
![img](figtabs/ch3/python_for_data_analysis_table4.8.png)

在数值计算方面，除了NumPy之外，SciPy也不得不提。SciPy 是基于 Numpy 开发的高级模块，包含线性代数、优化、集成和统计等模块，用于解决科学计算中的一些标准问题。例如数值积分和微分方程求解，扩展的矩阵计算，最优化，概率分布和统计函数，甚至包括信号处理等。在本课程中涉及相对较少，在此不展开，请同学们自行阅读。